[program:alimpay]
command=php /var/www/html/plugins/alimpay/server.php
directory=/var/www/html/plugins/alimpay
user=www-data
autostart=true
autorestart=true
startsecs=0
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
