[program:alipaycode]
command=/bin/sh -c "exec php /var/www/html/plugins/alipaycode/server.php $ALIPAYCODE_CHANNEL"
directory=/var/www/html/plugins/alipaycode
user=www-data
autostart=true
autorestart=true
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
