[program:alipaycode]
command=/bin/sh -c "[ -z \"$ALIPAYCODE_CHANNEL\" ] && exit 0; exec php /var/www/html/plugins/alipaycode/server.php $ALIPAYCODE_CHANNEL"
directory=/var/www/html/plugins/alipaycode
user=www-data
autostart=true
autorestart=unexpected
startsecs=0
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
